language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s "c0559cbf-70ca-4684-9416-57c53362b7df" -t "02b7393f427dac411e2f9de6ba3ba39456292bef70eda24f4dcc6081bf78b197" -p ./build
  skip_cleanup: true
  on:
    branch: master
